services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASS}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASS}
      MARIADB_DATABASE: ${MARIADB_DB}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  app:
    build: .
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "88:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client:/usr/share/nginx/html:ro
    depends_on:
      app:
       condition: service_started
    restart: unless-stopped
        
volumes:
  mariadb_data:
